### ISSUE TITLE
m3 Import Doesn't Support HoTS/Heroes version 26

### ISSUE THREAD

**Issue by ambugger** [flo/m3addon#14]
Heroes of the Storm and Heart of the Swarm newer models not able to be imported due to new model version, but it's not impossible, it seems to be trying. 

When you import, error message "Exception: There were __ unknown sections" appears. Size of version 26 is "820", but readme plus what it gives you is 464. Following readme section to enter "464" into version 26 in the Structures.xml file you get:

Read new prefs: C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blende
r\2.69\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.69\python
Import K:\sc2 extract\out1\m3\Models\Illidan.m3

Offsets of MODL in version 26:
0: modelName
12: flags
16: sequences
28: sequenceTransformationCollections
40: sequenceTransformationGroups
52: unknown00
56: unknown01
60: unknown02
64: unknown03
68: sts
80: bones
92: numberOfBonesToCheckForSkin
96: vFlags
100: vertices
112: divisions
124: boneLookup
136: boundings
164: maybeBoundingsFlags
168: unknown04
172: unknown05
176: unknown06
180: unknown07
184: unknown08
188: unknown09
192: unknown11
196: unknown12
200: unknown13
204: unknown14
208: unknown15
212: unknown16
216: unknown17
220: unknown18
224: unknown19
228: attachmentPoints
240: attachmentPointAddons
252: lights
264: shbxData
276: cameras
288: d
300: materialReferences
312: standardMaterials
324: displacementMaterials
336: compositeMaterials
348: terrainMaterials
360: volumeMaterials
372: unknownMaybeRef0
384: creepMaterials
396: volumeNoiseMaterials
408: splatTerrainBakeMaterial
420: particles
432: particleCopies
444: ribbons
456: projections
468: forces
480: warps
492: unknownMaybeRef1
504: rigidBodies
516: unknownMaybeRef2
528: physicalJoint
540: unknownMaybeRef4
552: ikjtData
564: unknownMaybeRef5
576: unknownbd5657bd
588: partsOfTurrentBehaviors
600: turrentBehaviors
612: absoluteInverseBoneRestPositions
624: tightHitTest
732: fuzzyHitTestObjects
744: attachmentVolumes
756: attachmentVolumesAddon0
768: attachmentVolumesAddon1
780: billboardBehaviors
792: tmdData
804: uniqueUnknownNumber
808: unknown45
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\__init__.py", line 4338, in execute
    m3import.importM3BasedOnM3ImportOptions(scene)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3import.py", line 1844, in importM3BasedOnM3Import
Options
    importer.importM3BasedOnM3ImportOptions(scene)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3import.py", line 397, in importM3BasedOnM3ImportO
ptions
    self.model = m3.loadModel(fileName)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3.py", line 1176, in loadModel
    sections = loadSections(filename)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3.py", line 1113, in loadSections
    structureDescription = structureHistory.getVersion(indexEntry.version)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3.py", line 104, in getVersion
    structure = M3StructureDescription(self.name, version, usedFields, specified
Size, self)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.69\s
cripts\addons\m3addon-master\m3.py", line 142, in __init__
    raise Exception("Size mismatch: %s in version %d has been specified to have
size %d, but the calculated size was %d" % (structureName, structureVersion, spe
cifiedSize, calculatedSize))
Exception: Size mismatch: MODL in version 26 has been specified to have size 464
, but the calculated size was 820

location: <unknown location>:-1

location: <unknown location>:-1

Thoughts to get newer HotS models?

**Comment by Cannibal12w** [comment]
Hi,

Has there been any update on this?  I was trying to import a Heroes of the Storm model to 3d print and this still exists.  I made it further than above using the instructions in the Readme but now I'm getting "unpack_from requires a buffer of at least 4 bytes" from LAYR at offset 464 (line 646 in m3.py).  I don't code Python, nor fully understand Blender, so I'm out of my wheelhouse after printing some debug info.

If you still feel uncomfortable about exporting Heroes models, that's cool; I'm just having fun printing models from my favorite games.

**Comment by Ganonmaster** [comment]
I'm running into the same issue, @Cannibal12w. Here is my [modified structures.xml](https://gist.github.com/Ganonmaster/6acf6bfd6824285e8934) and the trace I'm getting.

Going back to the issues, I don't think Blizzard would do much about it. If people were to upload maps with the Heroes models to the SC2 arcade, at the end of the day, Blizzard still controls that so they could just remove it should they find the use of those assets disagreeable. When heroes comes out, will anyone bother creating a Heroes game mode for SC2 when the real thing is available for free? And if they do, would anyone care? I doubt there is much incentive for an SC2 map with the Heroes skins when it will *guarenteed* be an inferior experience to the full game. And when Legacy of the Void comes with a newer/the same version of the format as Heroes people would be able to convert them anyway. Unless they don't want people to make custom models for Legacy of the Void at all? Would the M3addon even breach any of Blizzard's policies? Tools like this are pretty much always fine for personal or educational use, and I would say that the burden lies with the person who uses the tools that they use it appropriately.

If that doesn't win you over, could you maybe give us some pointers on how to get these models working ourselves? I'm only looking to import the models into Blender for some still image renders and animations, and as far as I know Blizzard has usually been ok with that.

Thanks for your time!

**Comment by Ganonmaster** [comment]
It looks like an addon for importing the Heroes files has been released for 3ds Max. Would be nice to see the Blender addon updated! http://www.sc2mapster.com/assets/sc1-raynor-vulture/files/73-script-m3-import-script-by-tm-v-1-5/

**Comment by flo** [comment]
The definitions for the new structure verions have been added to the m3addon in order to support LotV models. Heros models might work now too...

**Comment by flo** [comment]
Ganonmaster: If you are interested in getting LotV models to work , I will gladly explain you how to find out what structure.xml modifications are necessary to get them working. I saw you defined your own one, if you put it in a branch of a fork of this project then I can review it more easily. The error you get should not occur, does this also happen with a LotV model?

**Comment by flo** [comment]
Closing old ticket...
