### ISSUE TITLE
'jagged' models

### ISSUE THREAD

**Issue by qwill** [flo/m3addon#18]
I'm trying to import a .m3 file from a SC2 MPQ into blender, I get a very jagged model in red as opposed to a smooth archer.

**Comment by flo** [comment]
Without an exact model name I can't help you. Ecept maybe for the color: Have a look at the console to find out where it is looking for textures. Also make sure that you have configured blender to show the textures and not just a color.

**Comment by flo** [comment]
Closing issue due to lack of feedback what model was affected.
