### ISSUE TITLE
Hots models to SC2 error

### ISSUE THREAD

**Issue by AlastorStrixEfuartus** [flo/m3addon#20]
Greetings

I just found this tool
http://www.sc2mapster.com/assets/heroes-m3-sc2-m3-converter/files/
as i know your tool flo doesnt work with herose models but this tool should convert it to sc2 model well
but when i converted it iv get error like this 

http://prntscr.com/86w5yi

do you think that there is chance to solve it someway ?

so if you want to have a look 
http://www91.zippyshare.com/v/pZ9tsGgb/file.html

I personaly tried 
"Storm_Hero_Nova_Base_v05.m3"
convert by "HeroesM3ToSc2M3.exe"
"Storm_Hero_Nova_Base_v05_Sc2.m3"
and then open and here i get that error

**Comment by DaloLorn** [comment]
Every LotV model I've tried so far is also broken. (For example, the cinematic Carrier model, or the Tal'Darim Nexus.)

**Comment by flo** [comment]
Direct import of LotV and thus also heros  models might work now, although most might still be broken.

**Comment by DaloLorn** [comment]
Well, most of the models I've tested work now. I pointed out a few exceptions in the commit, though.

**Comment by flo** [comment]
thanks, I will look at them later. Also if you are interested I could teach you how to fix them yourself.

**Comment by DaloLorn** [comment]
That'd probably be quite a bit of teaching, seeing as my understanding of Blender consists of importing a model, deleting unneeded meshes/armatures, and exporting for fine-tuning in MilkShape. :/

**Comment by DaloLorn** [comment]
More broken models: ShakurasWarpGate, BattlecruiserGiant (Gorgon), SMX2_Ulnar. Cerberus is also kind of broken - it imports, but some parts of the ship are rotated or otherwise misplaced, and deleting the armature only makes things significantly worse.

**Comment by flo** [comment]
The readme (shown also on main page) contains a detailed list of errors and how to fix them. Mostly just editing of the structure.xml file is needed.

**Comment by flo** [comment]
ShakurasWarpGate I can't find. Is it in LotV dependency?

**Comment by DaloLorn** [comment]
Void.SC2Campaign should be the dependency.

**Comment by flo** [comment]
BattlecruiserGiant and SMX2_Ulnar. should be importable.  SMX2_Ulnar contains a new lens flare material which cant be exported yet as to less is known about it.

**Comment by flo** [comment]
Cerberus can now also be imported

**Comment by DaloLorn** [comment]
Cerberus is still broken. Like I said last time, this isn't a matter of 'can it be imported', but 'can it be imported correctly'. The panels attached to the rear section of the ship are misplaced.

Might not be fixable on your end, though.

**Comment by DaloLorn** [comment]
Portraits for the Havoc (MonitorEx2) and Energizer (EnergizerEx2) are also failing to import.

**Comment by flo** [comment]
MonitorEx2 and EnergizerEx2 should be importable, although I am not sure if all of the camera data gets imported correctly.

**Comment by TGP97** [comment]
Can yuot teach me how to solve this? I don't really know what to do as I've tried to solve it the way you say in common errors and doesn't seem to work.
![blender](https://cloud.githubusercontent.com/assets/16067365/11456527/2f32ccae-968c-11e5-9f9d-3361be94d810.png)

**Comment by flo** [comment]
Closing old ticket...
