### ISSUE TITLE
No errors, but also no import

### ISSUE THREAD

**Issue by Zodiarc** [flo/m3addon#22]
Hi.

I downloaded the repo (as .zip) and installed it to Blender 2.69. If i try to import a StarCraft (campaign, high quality) model, i get no errors but also the viewport stays empty and there are no additional objects in the outliner. Tried it with Heart of the Swarm and Legacy of the Void models.
Edit: the only model working till now is Zeratul from Heart of the Swarm.

**Comment by flo** [comment]
There should be an error. Maybe you accidentally closed it, that can happen very easily in Blender. Also via menu it is possible to view previous errors and other logged messages.

There was a regression a few days ago I just fixed. They propably work now.

**Comment by flo** [comment]
Closing old ticket...
