### ISSUE TITLE
Need some teaching

### ISSUE THREAD

**Issue by TGP97** [flo/m3addon#23]
Hey, flo, I wonder if you could teach me how to solve this kind of problems, as I've tried to solve them as you say at the common errors secrtion but is not working. I'ts not the first time I get this error, so I'd like how to solve it by myself.
![2f32ccae-968c-11e5-9f9d-3361be94d810](https://cloud.githubusercontent.com/assets/16067365/11560986/5ab7aa30-99c4-11e5-9174-d611dcab018b.png)

**Comment by flo** [comment]
Hi, I improved the documentation (the Readme that is also shown at the first page).

If something is still unclear let me know.

**Comment by TGP97** [comment]
Thanks mate :)

**Comment by TGP97** [comment]
Managed to solve it. I can work with it via the xml tools. But Blender gives an strange error. I do not rly care as I don't direct use Blender, just this tools. Now it works on the Cutscene Editor (which it didn't, it just crashed the editor).
