### ISSUE TITLE
Thank you for this helpful addon, but I get an issue.

### ISSUE THREAD

**Issue by golemsmk** [flo/m3addon#26]
Hello, first at all, thank you for your add-on, I'm just a Blender user and I don't know about code much. This add-on helps me save a lot of time.

Recently, I found an issue with it. I imported a model into Blender, but somehow the animations are wrong, you can see it in the left part of the model. I think maybe this is a problem with bones's rotation.

The model link is here: https://drive.google.com/file/d/0Bz_3Z4IQl0whMWgwSGVPSk9RS28/view?usp=sharing

Again, thank you for your sharing, that's amazing. :+1:

**Comment by flo** [comment]
Sorry, I do not plan to continue maintaining this addon. Closing this ticket now.
