### ISSUE TITLE
Issue with WOL Models

### ISSUE THREAD

**Issue by toasty1231** [flo/m3addon#27]
Hey, thanks so much for making this addon!

Im trying to 3d print many of the SC2 models. Most of them cooperated, but I cannot get the SM_Armory_Siegetank to work! (this is the highly detailed model they show off in the hanger, it would be super useful!)

Im decently new to blender, so sorry if the solution is obvious. 

![err](https://cloud.githubusercontent.com/assets/20652160/17122352/b4689be6-52a8-11e6-9dc5-62717b580817.jpg)

**Comment by flo** [comment]
Sorry, I do not plan to continue maintaining this addon. Closing this ticket now.
