### ISSUE TITLE
Storymode Character Import Issue: incorrect expected-value, followed by out of range

### ISSUE THREAD

**Issue by CodeMonkey37** [flo/m3addon#29]
Hi Flo,

Thank you for the addon. It works great in the majority of cases, even some of the larger sets which I was not expecting, and was a pleasant surprise.

Unfortunately, it does not work with a number of the storymode models, primarily the protoss, the zerg, and Nova. Although it does work with Commander Raynor, and the storymode marine. (I'm primarily looking at the Wings of Liberty campaign units, though if I can get those working I might branch out to the others)

Steps taken:

Import Model > Unknown section MAT_V20

> > Added version 20 under MAT_ in the structures.xml file.

unknown2410d9f0 expected value "0x000000000000000000000000" but it was "0x0000000000000000ffffffff"

> > Changed value in structures.xml file

expected value "0x0000000000000000ffffffff" but it was "0xffffffff00000000b611deE"

From here it then broke unknownAt41, and after fixing that went onto throw "IndexError: List index out of range" which I have no idea how to fix.

This is the same error obtained if I change expected value, to default value, as I noticed you did in a number of fixes. If I leave the default settings in, the protoss models start throwing other exceptions such as "LFLR.sourceFilePath tries to reference 4 elements in a MODL section that contains just 1 element(s)"

Is there a way to grep the model files themselves for this information so I can properly update the structures file? If not, is there anyway I can help facilitate a fix?

Thank you.

**Comment by flo** [comment]
not sure if you are still interested. there are scripts for converting m3 to xml and vise versa called m3ToXml.py and xmlToM3.py which use the same structure.xml. so you can use those to have a look at the data.

**Comment by intelligide** [comment]
Is there any way to solve the problem ? Because i get the same error.

**Comment by intelligide** [comment]
I tried to debug and I get: 

```
1 86
2 86
3 86
5 86
13 86
16 86
18 86
26 86
27 86
32 86
33 86
34 86
85 86
4 86
8 86
6 86
7 86
9 86
10 86
11 86
12 86
14 86
15 86
17 86
19 86
20 86
21 86
22 86
23 86
24 86
25 86
28 86
30 86
31 86
29 86
35 86
1061997773 86
```

The first number is the ref.index and the second is the sections list length.

It seems that it only happens with SMX3_ models. Blizzard may have changed M3 format.

**Comment by flo** [comment]
Possibly the index field is not 32 bit, but just 16 bit and another 16 bit field that comes afterwards contained now some value. That would explain the large value. I have no interest in investigating further but since you are trying I wanted to give you a hint.

**Comment by flo** [comment]
Sorry, I do not plan to continue maintaining this addon. Closing this ticket now.
