### ISSUE TITLE
[Issue] Transfer Animations: The animations / the m3a file has not been made for the m3 file

### ISSUE THREAD

**Issue by bknie1** [flo/m3addon#30]
Hi, I've managed to import Murky (Heroes of the Storm) into Blender but his animations are stuck in the associated m3a file. Importing the m3a file separately creates a second Armature Object. I can see the parts moving but I need to merge the two so that the body moves.

How do you use the m3 and m3a merging functionality? I'm having some trouble:

Ah, right, so I'm running the script separately from Blender. No big deal. However I'm having a problem:

```
C:\>python transferAnimations.py MurkyBase.m3 MurkyAnims.m3a Murky.m3
The animations / the m3a file has not been made for the m3 file
```

Thanks!

**Comment by bknie1** [comment]
Ah, right, so I'm running the script separately from Blender. No big deal. However:

```
C:\>python C:\Users\...\transferAnimations.py *m3 *m3a output
Traceback (most recent call last):
  File "C:\...\transferAnimations.py", line 23, in <module>
    import m3
ImportError: No module named 'm3'
```

I'm receiving this error despite indicating the m3 and m3a files.

**Comment by bknie1** [comment]
This seems to be because of the line:

`if m3Model.uniqueUnknownNumber != m3aModel.uniqueUnknownNumber:`

**Comment by flo** [comment]
Sorry, I do not plan to continue maintaining this addon. Closing this ticket now.
