### ISSUE TITLE
Matrix does not have an inverse error

### ISSUE THREAD

**Issue by melchorc** [flo/m3addon#36]
This plugin was great although I am having trouble opening old modified .m3 models.
I am importing Ghostnova Models from SC2Mapster Link: https://www.sc2mapster.com/projects/ghostnovas-mods/files/638740. I think this model was created/modified by 3DSMax M3 Plugin. 
![crucialerror](https://user-images.githubusercontent.com/11401138/29752134-e5f47c04-8b8a-11e7-826b-928d4d6050f9.png)

**Comment by flo** [comment]
Sorry, I do not plan to continue maintaining this addon. Closing this ticket now.
