### ISSUE TITLE
Export no longer works?

### ISSUE THREAD

**Issue by kill23445** [flo/m3addon#37]
Tried to import a model and then export directly after importing and it always came up with a error even if I  tried to export just the single default cube it comes up with

**Comment by kill23445** [comment]
https://imgur.com/a/7i9wQ

**Comment by Talv** [comment]
You should've at least provide model name - it's hard to troubleshot otherwise.

Perhaps it has been imported with errors - some material data missing. You could probably fix it by hand, and then exporter would work.

**Comment by flo** [comment]
@Talv  thanks for answering this. The error message tells you btw. that a specific mesh has indeed no material.

Closing this now as I don't plan to continue maintaining this addon.
